version: '3.8'

services:
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: cinema-postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:Mishka@host.docker.internal:5433/cinema_db?sslmode=disable"
    volumes:
      - ./queries.yaml:/queries.yaml
    command:
      - "--extend.query-path=/queries.yaml"
      - "--log.level=info"
    ports:
      - "9187:9187"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: cinema-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
    depends_on:
      - postgres_exporter
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.1.5
    container_name: cinema-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    depends_on:
      - prometheus
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  monitoring:
    driver: bridge
volumes:
  grafana_data:
  prometheus_data:

