global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # postgres-exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s

  # Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    scrape_interval: 5s